In [ ]:
import numpy as np
import torch


## What is a Tensor?


A Tensor is the generalization of a vector into k dimensions.

![](https://miro.medium.com/max/644/1*SGqhI_WpSaEr17wo8ycUhg.png)
Table taken from [1].

Because of this, a tensor is any k-dimensional structure, including matrices, vectors and scalars. PyTorch is a deep learning framework (https://pytorch.org) widely used for both research and production. As in any other deep learning framework, its core data structure is the tensor.

In [ ]:
a = torch.empty(5, 7)
print(a)
print(a.shape)

tensor([[1.3584e-36, 0.0000e+00, 0.0000e+00, 1.4013e-45, 9.1835e-41, 0.0000e+00,
         1.4013e-45],
        [2.3694e-38, 0.0000e+00, 3.6013e-43, 2.3694e-38, 0.0000e+00, 3.6013e-43,
         2.3694e-38],
        [0.0000e+00, 3.6013e-43, 9.1835e-41, 0.0000e+00, 3.6013e-43, 2.3694e-38,
         0.0000e+00],
        [3.6013e-43, 2.3694e-38, 0.0000e+00, 1.4013e-45, 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00]])
torch.Size([5, 7])


In [ ]:
a.fill_(42)

tensor([[42., 42., 42., 42., 42., 42., 42.],
        [42., 42., 42., 42., 42., 42., 42.],
        [42., 42., 42., 42., 42., 42., 42.],
        [42., 42., 42., 42., 42., 42., 42.],
        [42., 42., 42., 42., 42., 42., 42.]])

In [ ]:
print(a)

tensor([[42., 42., 42., 42., 42., 42., 42.],
        [42., 42., 42., 42., 42., 42., 42.],
        [42., 42., 42., 42., 42., 42., 42.],
        [42., 42., 42., 42., 42., 42., 42.],
        [42., 42., 42., 42., 42., 42., 42.]])


In [ ]:
a = torch.eye(5, 5)
print(a)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


### Exercise 1

Create a tensor *z* drawn from a Gaussian distribution of dimensions (16, 1024)

In [ ]:
z = torch.randn(16 ,1024)
print(z.shape)

torch.Size([16, 1024])


In [ ]:
z.std()

tensor(0.9954)

# Data types

In [ ]:
z = z.float()
z.dtype

torch.float32

In [ ]:
a = z.long()
a.dtype

torch.int64

In [ ]:
z.round()

tensor([[ 1., -1.,  1.,  ..., -0., -1., -1.],
        [-3.,  1., -1.,  ..., -0.,  1.,  1.],
        [ 1., -0., -2.,  ..., -1., -2.,  0.],
        ...,
        [ 0., -1.,  2.,  ..., -0.,  1.,  0.],
        [-0.,  1., -1.,  ...,  0., -1., -0.],
        [-0.,  1., -0.,  ...,  1.,  0.,  0.]], dtype=torch.float64)

In [ ]:
z.int8()

AttributeError: ignored

In [ ]:
torch.tensor(np.zeros([5, 5, 3]))

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64)

In [ ]:
l = [[1, 2], [3, 4]]
a = torch.tensor(l)
print(a)
print(a.shape)

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])


In [ ]:
x = torch.tensor(np.zeros([5, 5, 3]))
print(x.shape)

torch.Size([5, 5, 3])


In [ ]:
x.numpy()

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

### Exercise 2

Create an **int16** *it* tensor in PyTorch (however you want) from the following numpy array *na*

In [ ]:
na = 10 * np.random.rand(8, 8)

#TODO: create the short tensor out of 'na'
it2 = torch.tensor(na, dtype=torch.int16)
it = torch.tensor(na)
it = it.short()


# Assertion to ensure it is the desired data type
assert it.dtype == torch.int16, 'this tensor is not of dtype short? =('

In [ ]:
a = torch.empty(2, 2)
a.fill_(1)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [ ]:
a = torch.sin((a + 1)**2)
a

tensor([[-0.5291, -0.5291],
        [-0.5291, -0.5291]])

![](https://www.researchgate.net/profile/Haroldo_Campos_Velho2/publication/235901708/figure/fig1/AS:669443441049602@1536619162135/Artificial-neuron-Equation-neuron-output.ppm)

In [ ]:
x = torch.ones(1, 1000)

w = 0.01*torch.randn(1000, 1)

b = torch.tensor(10)

def forward(x, w, b):
    h = x.mm(w) + b
    y = h.clamp(min=0)
    return y

print(forward(x, w, b))

tensor([[10.0901]])


In [ ]:
def forward(x, w, b):
    h = x.mm(w) + b
    return h.clamp_(min=0)
print(forward(x, w, b))

tensor([[10.0901]])


#### Transpositions and beyond

In [ ]:
a = torch.empty(10, 20, 5)
print(a.shape)

a = a.transpose(1, 2)

print(a.shape)

a = a.transpose(0, 2)

print(a.shape)

torch.Size([10, 20, 5])
torch.Size([10, 5, 20])
torch.Size([20, 5, 10])


In [ ]:
b = a.reshape(200, 5)
print(b.shape)

b = a.reshape(1, 2, 5, 20, 5)

print(b.shape)

torch.Size([200, 5])
torch.Size([1, 2, 5, 20, 5])


In [ ]:
a = torch.empty(5, 20, 5)

chunks = torch.chunk(a, 5, dim=1)

In [ ]:
torch.cat(chunks).shape

torch.Size([25, 4, 5])

In [ ]:
torch.cat?

# Neural network from the Backpropagation theory

In [ ]:
x = torch.tensor([[-1, 2]], dtype=torch.float32)
print(f"Shape of x: {x.shape}")

w = torch.tensor([[2], [-3]], dtype=torch.float32)
print(f"Shape of w: {w.shape}")

b = torch.tensor(-3, dtype=torch.float32)
print(f"Shape of b: {b.shape}")

def forward(x, w, b):
    h = x.mm(w) + b
    y = torch.sigmoid(h)
    return y

print(f"Output: {forward(x, w, b)}")

Shape of x: torch.Size([1, 2])
Shape of w: torch.Size([2, 1])
Shape of b: torch.Size([])
Output: tensor([[1.6701e-05]])
